# Generated by Django 5.2.1 on 2025-05-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('menu_name', models.CharField(max_length=50)),
                ('named_url', models.CharField(blank=True, max_length=200, null=True)),
                ('explicit_url', models.CharField(blank=True, max_length=200, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('slug', 'menu_name'), name='unique_slug_per_menu')],
            },
        ),
    ]
